spring.application.name=ApiGateway

server.port=8090

spring.security.oauth2.client.registration.gateway-client.client-id=gateway-client
spring.security.oauth2.client.registration.gateway-client.client-secret=36nOoVOferkRYGpmCNNzdq3JqOIWwALI
spring.security.oauth2.client.registration.gateway-client.client-authentication-method=client_secret_basic
spring.security.oauth2.client.registration.gateway-client.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.gateway-client.redirect-uri={baseUrl}/login/oauth2/code/gateway-client
spring.security.oauth2.client.registration.gateway-client.scope=openid,profile,email,roles
spring.security.oauth2.client.registration.gateway-client.provider=keycloak

spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:9090/realms/file-management

backend.file-service-url=http://localhost:8082
backend.user-service-url=http://localhost:8081
