spring.application.name=FileService

spring.mvc.problemdetails.enabled=true

# Expose health endpoint under /actuator/health
management.endpoints.web.exposure.include=health
management.endpoints.web.base-path=/actuator
management.endpoint.health.show-details=always

spring.datasource.url=jdbc:postgresql://localhost:5432/files_db
spring.datasource.username=file_user
spring.datasource.password=file_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=public
spring.flyway.table=flyway_schema_history

minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket=uploads

# Logging Configuration
logging.level.root=INFO
logging.level.it.polito.wa2.fileservice=INFO
logging.level.it.polito.wa2.fileservice.services.UploadService=INFO
logging.level.it.polito.wa2.fileservice.controllers.BasicController=INFO
logging.level.it.polito.wa2.fileservice.exception.ProblemDetailsHandler=WARN
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=WARN

springdoc.swagger-ui.path=/openapi/swagger-ui.html
springdoc.api-docs.path=/openapi/v1/api-docs
springdoc.paths-to-match=/**

user.service.url=http://localhost:8081

# AI Processing Service Configuration (Step 7 - RAG)
ai.processing.service.url=http://localhost:8084

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/file-management

# Service account for machine-to-machine communication
keycloak.client-id=fileservice-client
keycloak.client-secret=1nM5I4V7PjxymCTlESdqigv17Ceh9NpN
keycloak.token-uri=http://localhost:9090/realms/file-management/protocol/openid-connect/token

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

server.port=8082
